version: '3.8'

services:
  frps:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frp-server
    restart: unless-stopped
    
    # Network configuration
    ports:
      - "7000:7000"    # FRP control port
      - "80:80"        # HTTP
      - "443:443"      # HTTPS
      - "7500:7500"    # Dashboard (optional)
    
    # Environment variables
    environment:
      - FRP_AUTH_TOKEN=${FRP_AUTH_TOKEN:-change_this_token}
      - FRP_SUBDOMAIN_HOST=${FRP_SUBDOMAIN_HOST:-}
      - FRP_DASHBOARD_ENABLED=${FRP_DASHBOARD_ENABLED:-false}
      - FRP_DASHBOARD_USER=${FRP_DASHBOARD_USER:-admin}
      - FRP_DASHBOARD_PASSWORD=${FRP_DASHBOARD_PASSWORD:-change_this_password}
      - SSL_ENABLED=${SSL_ENABLED:-false}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-}
      - LETSENCRYPT_DOMAINS=${LETSENCRYPT_DOMAINS:-}
    
    # Volume mounts
    volumes:
      - frp_config:/etc/frp
      - frp_logs:/var/log/frp
      - letsencrypt_certs:/etc/letsencrypt
      - ./custom-config:/etc/frp/custom:ro  # Optional custom config
    
    # Security
    user: "1000:1000"  # Run as non-root user
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7500/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Nginx reverse proxy for SSL termination
  nginx:
    image: nginx:alpine
    container_name: frp-nginx
    restart: unless-stopped
    profiles:
      - nginx
    
    ports:
      - "80:80"
      - "443:443"
    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - letsencrypt_certs:/etc/letsencrypt:ro
      - nginx_logs:/var/log/nginx
    
    depends_on:
      - frps
    
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Certbot for SSL certificate management
  certbot:
    image: certbot/certbot
    container_name: frp-certbot
    restart: "no"
    profiles:
      - ssl
    
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_www:/var/www/certbot
    
    command: >
      sh -c "
        if [ -n \"$$LETSENCRYPT_EMAIL\" ] && [ -n \"$$LETSENCRYPT_DOMAINS\" ]; then
          certbot certonly --webroot --webroot-path=/var/www/certbot
          --email $$LETSENCRYPT_EMAIL --agree-tos --no-eff-email
          -d $$LETSENCRYPT_DOMAINS
        else
          echo 'LETSENCRYPT_EMAIL and LETSENCRYPT_DOMAINS must be set'
          exit 1
        fi
      "
    
    environment:
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_DOMAINS=${LETSENCRYPT_DOMAINS}

volumes:
  frp_config:
    driver: local
  frp_logs:
    driver: local
  letsencrypt_certs:
    driver: local
  letsencrypt_www:
    driver: local
  nginx_logs:
    driver: local

networks:
  default:
    name: frp-network
    driver: bridge
